import Ember from 'ember';

const publications = [
    {"id":73439,"title":"Decentralized Optimal Frequency Control of Interconnected Power Systems with Transient Constraints","book_title":"55th Conference on Decision and Control (CDC), 2016","event_title":"IEEE 55th Conference on Decision and Control (CDC)","creators":[{"orcid":null,"name":{"lineage":null,"given":"Zhaojian","honourific":null,"family":"Wang"},"id":"Wang-Zhaojian"},{"orcid":null,"name":{"lineage":null,"given":"Feng","honourific":null,"family":"Liu"},"id":"Liu-Feng"},{"orcid":"0000-0001-6476-3048","name":{"lineage":null,"given":"Steven H.","honourific":null,"family":"Low"},"id":"Low-S-H"},{"orcid":"0000-0003-0539-8591","name":{"lineage":null,"given":"Changhong","honourific":null,"family":"Zhao"},"id":"Zhao-Changhong"},{"orcid":null,"name":{"lineage":null,"given":"Shengwei","honourific":null,"family":"Mei"},"id":"Mei-Shengwei"}],"isbn":"978-1-5090-1838-3","ispublished":"pub","date":"2016-12","pagerange":"664-671","datestamp":"2017-01-20 07:12:02","place_of_pub":"Piscataway, NJ","publisher":"IEEE","official_url":"http://resolver.caltech.edu/CaltechAUTHORS:20170111-135813725"},

    {"id":78177,"title":"Optimal Placement of Energy Storage in Distribution Networks","creators":[{"orcid":"0000-0002-4921-8372","name":{"lineage":null,"given":"Yujie","honourific":null,"family":"Tang"},"id":"Tang-Yujie"},{"orcid":"0000-0001-6476-3048","name":{"lineage":null,"given":"Steven H.","honourific":null,"family":"Low"},"id":"Low-S-H"}],"ispublished":"pub","issn":"1949-3053","date":"2017-11","pagerange":"3094-3103","datestamp":"2017-06-14 01:52:35","publication":"IEEE Transactions on Smart Grid","publisher":"IEEE","official_url":"http://resolver.caltech.edu/CaltechAUTHORS:20170613-162646711","volume":8,"number":6},

{"id":77462,"title":"Smoothed Least-laxity-first Algorithm for EV Charging","book_title":"e-Energy '17 Proceedings of the Eighth International Conference on Future Energy Systems","event_title":"Eighth International Conference on Future Energy Systems","creators":[{"orcid":null,"name":{"lineage":null,"given":"Yorie","honourific":null,"family":"Nakahira"},"id":"Nakahira-Yorie"},{"orcid":"0000-0002-2289-9737","name":{"lineage":null,"given":"Niangjun","honourific":null,"family":"Chen"},"id":"Chen-Niangjun"},{"orcid":null,"name":{"lineage":null,"given":"Lijun","honourific":null,"family":"Chen"},"id":"Chen-Lijun"},{"orcid":null,"name":{"lineage":null,"given":"Steven H.","honourific":null,"family":"Low"},"id":"Low-S-H"}],"isbn":"978-1-4503-5036-5","ispublished":"pub","date":"2017-05","pagerange":"242-251","datestamp":"2017-05-16 22:07:08","place_of_pub":"New York, NY","publisher":"ACM","official_url":"http://resolver.caltech.edu/CaltechAUTHORS:20170515-140123828"},

{"creators":[{"name":{"given":"Linqi","family":"Guo"}},{"name":{"given":"Erliksson","family":"Karl"}},{"name":{"given":"Steven","family":"Low"}}],"title":"Optimal Online Adaptive Electric Vehicle Charging", "book_title": "Proceedings of the IEEE Power and Energy Society General Meeting","event_title": "Proceedings of the IEEE Power and Energy Society General Meeting","place_of_pub":"Chicago, IL", "publisher":"IEEE", "date":"2017-07"},

{"id":74410,"title":"The role of strong convexity-concavity in the convergence and robustness of the saddle-point dynamics","book_title":"54th Annual Allerton Conference on Communication, Control, and Computing","event_title":"54th Annual Allerton Conference on Communication, Control, and Computing","creators":[{"orcid":null,"name":{"lineage":null,"given":"Ashish","honourific":null,"family":"Cherukuri"},"id":"Cherukuri-A"},{"orcid":"0000-0003-1568-1833","name":{"lineage":null,"given":"Enrique","honourific":null,"family":"Mallada"},"id":"Mallada-E"},{"orcid":"0000-0001-6476-3048","name":{"lineage":null,"given":"Steven","honourific":null,"family":"Low"},"id":"Low-S-H"},{"orcid":null,"name":{"lineage":null,"given":"Jorge","honourific":null,"family":"Cortés"},"id":"Cortés-J"}],"isbn":"978-1-5090-4550-1","ispublished":"pub","date":"2016-09","pagerange":"504-510","datestamp":"2017-02-18 03:50:47","place_of_pub":"Piscataway, NJ","publisher":"IEEE","official_url":"http://resolver.caltech.edu/CaltechAUTHORS:20170217-154230896"},

{"id":79461,"title":"Distributed Frequency Control with Operational Constraints, Part I: Per-Node Power Balance","creators":[{"orcid":null,"name":{"lineage":null,"given":"Zhaojian","honourific":null,"family":"Wang"},"id":"Wang-Zhaojian"},{"orcid":null,"name":{"lineage":null,"given":"Feng","honourific":null,"family":"Liu"},"id":"Liu-Feng"},{"orcid":"0000-0001-6476-3048","name":{"lineage":null,"given":"Steven H.","honourific":null,"family":"Low"},"id":"Low-S-H"},{"orcid":"0000-0003-0539-8591","name":{"lineage":null,"given":"Changhong","honourific":null,"family":"Zhao"},"id":"Zhao-Changhong"},{"orcid":null,"name":{"lineage":null,"given":"Shengwei","honourific":null,"family":"Mei"},"id":"Mei-Shengwei"}],"ispublished":"inpress","issn":"1949-3053","date":"2017-07-25","datestamp":"2017-07-26 23:25:57","publication":"IEEE Transactions on Smart Grid","publisher":"IEEE","official_url":"http://resolver.caltech.edu/CaltechAUTHORS:20170726-160828931"},

{"id":79458,"title":"Distributed Frequency Control with Operational Constraints, Part II: Network Power Balance","creators":[{"orcid":null,"name":{"lineage":null,"given":"Zhaojian","honourific":null,"family":"Wang"},"id":"Wang-Zhaojian"},{"orcid":null,"name":{"lineage":null,"given":"Feng","honourific":null,"family":"Liu"},"id":"Liu-Feng"},{"orcid":"0000-0001-6476-3048","name":{"lineage":null,"given":"Steven H.","honourific":null,"family":"Low"},"id":"Low-S-H"},{"orcid":"0000-0003-0539-8591","name":{"lineage":null,"given":"Changhong","honourific":null,"family":"Zhao"},"id":"Zhao-Changhong"},{"orcid":null,"name":{"lineage":null,"given":"Shengwei","honourific":null,"family":"Mei"},"id":"Mei-Shengwei"}],"ispublished":"inpress","issn":"1949-3053","date":"2017-07-25","datestamp":"2017-07-26 23:01:47","publication":"IEEE Transactions on Smart Grid","publisher":"IEEE","official_url":"http://resolver.caltech.edu/CaltechAUTHORS:20170726-155035857"},

 {"id":79448,"title":"A Survey of Distributed Optimization and Control Algorithms for Electric Power Systems","creators":[{"orcid":null,"name":{"lineage":null,"given":"Daniel K.","honourific":null,"family":"Molzahn"},"id":"Molzahn-D-K"},{"orcid":null,"name":{"lineage":null,"given":"Florian","honourific":null,"family":"Dörfler"},"id":"Dörfler-F"},{"orcid":null,"name":{"lineage":null,"given":"Henrik","honourific":null,"family":"Sandberg"},"id":"Sandberg-H"},{"orcid":"0000-0001-6476-3048","name":{"lineage":null,"given":"Steven H.","honourific":null,"family":"Low"},"id":"Low-S-H"},{"orcid":null,"name":{"lineage":null,"given":"Sambuddha","honourific":null,"family":"Chakrabarti"},"id":"Chakrabarti-S"},{"orcid":null,"name":{"lineage":null,"given":"Ross","honourific":null,"family":"Baldick"},"id":"Baldick-R"},{"orcid":null,"name":{"lineage":null,"given":"Javad","honourific":null,"family":"Lavaei"},"id":"Lavaei-J"}],"ispublished":"pub","issn":"1949-3053","date":"2017-11","pagerange":"2941-2962","datestamp":"2017-07-26 22:21:20","publication":"IEEE Transactions on Smart Grid","publisher":"IEEE","official_url":"http://resolver.caltech.edu/CaltechAUTHORS:20170726-151527403","volume":8,"number":6},

{"id":73444,"title":"Optimal placement of energy storage in distribution networks","book_title":"IEEE 55th Conference on Decision and Control (CDC)","event_title":"IEEE 55th Conference on Decision and Control (CDC)","creators":[{"name":{"lineage":null,"given":"Yujie","honourific":null,"family":"Tang"},"id":"Tang-Yujie"},{"name":{"lineage":null,"given":"Steven H.","honourific":null,"family":"Low"},"id":"Low-S-H"}],"isbn":"978-1-5090-1837-6","ispublished":"pub","date":"2016-12","pagerange":"3258-3264","datestamp":"2017-01-20 00:56:41","place_of_pub":"Piscataway, NJ","publisher":"IEEE","official_url":"http://resolver.caltech.edu/CaltechAUTHORS:20170111-145514472"},

{"id":77530,"title":"Real-time Optimal Power Flow","creators":[{"orcid":"0000-0002-4921-8372","name":{"lineage":null,"given":"Yujie","honourific":null,"family":"Tang"},"id":"Tang-Yujie"},{"orcid":null,"name":{"lineage":null,"given":"Krishnamurthy","honourific":null,"family":"Dvijotham"},"id":"Dvijotham-K"},{"orcid":"0000-0001-6476-3048","name":{"lineage":null,"given":"Steven","honourific":null,"family":"Low"},"id":"Low-S-H"}],"ispublished":"pub","issn":"1949-3053","date":"2017-11","pagerange":"2963-2973","datestamp":"2017-05-17 22:14:39","publication":"IEEE Transactions on Smart Grid","publisher":"IEEE","official_url":"http://resolver.caltech.edu/CaltechAUTHORS:20170517-150114536","volume":8,"number":6},

{"id":80095,"title":"Profit Maximizing Planning and Control of Battery Energy Storage Systems for Primary Frequency Control","creators":[{"orcid":null,"name":{"lineage":null,"given":"Ying Jun","honourific":null,"family":"Zhang"},"id":"Zhang-Ying-Jun"},{"orcid":"0000-0003-0539-8591","name":{"lineage":null,"given":"Changhong","honourific":null,"family":"Zhao"},"id":"Zhao-Changhong"},{"orcid":null,"name":{"lineage":null,"given":"Wanrong","honourific":null,"family":"Tang"},"id":"Tang-Wanrong"},{"orcid":"0000-0001-6476-3048","name":{"lineage":null,"given":"Steven H.","honourific":null,"family":"Low"},"id":"Low-S-H"}],"ispublished":"inpress","issn":"1949-3053","date":"2016-05-04","datestamp":"2017-08-10 18:25:54","publication":"IEEE Transactions on Smart Grid","publisher":"IEEE","official_url":"http://resolver.caltech.edu/CaltechAUTHORS:20170810-105250761"},

{"id":82832,"title":"Optimal Load-side Control for Frequency Regulation in Smart Grids","creators":[{"orcid":"0000-0003-1568-1833","name":{"lineage":null,"given":"Enrique","honourific":null,"family":"Mallada"},"id":"Mallada-E"},{"orcid":"0000-0003-0539-8591","name":{"lineage":null,"given":"Changhong","honourific":null,"family":"Zhao"},"id":"Zhao-Changhong"},{"orcid":"0000-0001-6476-3048","name":{"lineage":null,"given":"Steven","honourific":null,"family":"Low"},"id":"Low-S-H"}],"ispublished":"inpress","issn":"0018-9286","date":"2017-06-08","datestamp":"2017-11-01 19:43:50","publication":"IEEE Transactions on Automatic Control","publisher":"IEEE","official_url":"http://resolver.caltech.edu/CaltechAUTHORS:20171101-115726975"},

{"id":68953,"title":"Distributed Optimal Power Flow Algorithm for Radial Networks, I: Balanced Single Phase Case","creators":[{"name":{"lineage":null,"given":"Qiuyu","honourific":null,"family":"Peng"},"id":"Peng-Qiuyu"},{"name":{"lineage":null,"given":"Steven H.","honourific":null,"family":"Low"},"id":"Low-S-H"}],"ispublished":"inpress","issn":"1949-3053","date":"2016-03-24","datestamp":"2016-07-25 22:57:45","publication":"IEEE Transactions on Smart Grid","publisher":"IEEE","official_url":"http://resolver.caltech.edu/CaltechAUTHORS:20160711-103700266"},

{"creators":[{"name":{"given":"Yujie","family":"Tang"}},{"name":{"given":"Steven","family":"Low"}}],"title":"Distributed algorithm for time-varying optimal power flow", "book_title": "Proceedings of 56th IEEE Conference on Decision and Control","place_of_pub":"Melbourne, Australia", "publisher":"IEEE", "date":"2017-12", "event_title": "56th Conference on Decision and Control (CDC)"},

{"creators":[{"name":{"given":"Linqi","family":"Guo"}},{"name":{"given":"Steven","family":"Low"}}],"title":"Spectral characterization of controllability and observability for frequency regulation dynamics", "book_title": "Proceedings of 56th IEEE Conference on Decision and Control","place_of_pub":"Melbourne, Australia", "publisher":"IEEE", "date":"2017-12", "event_title": "56th Conference on Decision and Control (CDC)"},

{"creators":[{"name":{"given":"Pengcheng","family":"You"}},{"name": {'given':'John', 'family':'Pang'}},{'name':{'given':'Minghua', 'family':"Chen"}},{"name":{"given":"Steven","family":"Low"}}, {"name": {"given":"Youxian", "family":"Sun"}}],"title":"Battery swapping assignment for electric cehicles: a bipartite matching approach", "book_title": "Proceedings of 56th IEEE Conference on Decision and Control","place_of_pub":"Melbourne, Australia", "publisher":"IEEE", "date":"2017-12", "event_title": "56th Conference on Decision and Control (CDC)"},
    
{"creators":[{"name":{"given":"John","family":"Doyle"}},{"name": {"given": "Nikolai", "family": "Matni"}},{"name": {"given":"James","family":"Anderson"}},{"name":{"given":"Steven","family":"Low"}}],"title":"A system level approach to controller synthesis", "book_title": "Proceedings of 56th IEEE Conference on Decision and Control","place_of_pub":"Melbourne, Australia", "publisher":"IEEE", "date":"2017-12", "event_title": "56th Conference on Decision and Control (CDC)"},

{"creators":[{"name":{"given":"Linqi","family":"Guo"}},{"name": {"given":"Chen", "family":"Liang"}},{"name":{"given":"Steven","family":"Low"}}],"title":"Monotonicity Properties and Spectral Characterization of Power Redistribution in Cascading Failures", "book_title": "Proceedings of 55th Annual Allerton Conference on Communication, Control, and Computing","place_of_pub":"Monticello, IL", "publisher":"IEEE", "date":"2017-10", "event_title": "55th Annual Allerton Conference on Communication, Control, and Computing"},

{"creators":[{"name":{"given":"Changhong","family":"Zhao"}},{"name": {"given": "Emiliano", "family":"Dall'Anese"}},{"name":{"given":"Steven","family":"Low"}}],"title":"Convex relaxation of OPF in multiphase radial networks with Delta connection", "book_title": "Proceedings of the 10th Bulk Power Systems Dynamics and Control Symposium","place_of_pub":"Espinho, Portugal", "date":"2017-08", "event_title": "Proceedings of the 10th Bulk Power Systems Dynamics and Control Symposium"},

{"id":53449,"title":"The Economics of the Cloud: Price Competition and Congestion","creators":[{"name":{"lineage":null,"given":"Jonatha","honourific":null,"family":"Anselmi"},"id":"Anselmi-J"},{"name":{"lineage":null,"given":"Danilo","honourific":null,"family":"Ardagna"},"id":"Ardagna-D"},{"name":{"lineage":null,"given":"John C. S.","honourific":null,"family":"Lui"},"id":"Lui-John-C-S"},{"name":{"lineage":null,"given":"Adam","honourific":null,"family":"Wierman"},"id":"Wierman-A"},{"name":{"lineage":null,"given":"Yunjian","honourific":null,"family":"Xu"},"id":"Xu-Yunjian"},{"name":{"lineage":null,"given":"Zichao","honourific":null,"family":"Yang"},"id":"Yang-Zichao"}],"ispublished":"pub","issn":"1551-9031","date":"2014-06","pagerange":"58-63","datestamp":"2015-01-09 16:27:33","publication":"ACM SIGecom Exchanges","publisher":"Association for Computing Machinery","official_url":"http://resolver.caltech.edu/CaltechAUTHORS:20150109-074030107","volume":13,"number":1},

{"id":80379,"title":"Controlling the Variability of Capacity Allocations Using Service Deferrals","creators":[{"name":{"lineage":null,"given":"Andres","honourific":null,"family":"Ferragut"},"id":"Ferragut-A"},{"name":{"lineage":null,"given":"Fernando","honourific":null,"family":"Paganini"},"id":"Paganini-F"},{"name":{"lineage":null,"given":"Adam","honourific":null,"family":"Wierman"},"id":"Wierman-A"}],"ispublished":"pub","issn":"2376-3639","date":"2017-08","pagerange":"Art. No. 15","datestamp":"2017-08-14 22:18:54","publication":"ACM Transactions on Modeling and Performance Evaluation of Computing Systems","publisher":"ACM","official_url":"http://resolver.caltech.edu/CaltechAUTHORS:20170814-150846810","volume":2,"number":3},

{"id":78219,"title":"A Spot Capacity Market to Increase Power Infrastructure Utilization in Multi-Tenant Data Centers","book_title":"Proceedings of the 2017 ACM SIGMETRICS / International Conference on Measurement and Modeling of Computer Systems - SIGMETRICS '17 Abstracts","event_title":"2017 ACM SIGMETRICS / International Conference on Measurement and Modeling of Computer Systems","creators":[{"name":{"lineage":null,"given":"Mohammad A.","honourific":null,"family":"Islam"},"id":"Islam-M-A"},{"name":{"lineage":null,"given":"Xiaoqi","honourific":null,"family":"Ren"},"id":"Ren-Xiaoqi"},{"name":{"lineage":null,"given":"Shaolei","honourific":null,"family":"Ren"},"id":"Ren-Shaolei"},{"name":{"lineage":null,"given":"Adam","honourific":null,"family":"Wierman"},"id":"Wierman-A"}],"isbn":"978-1-4503-5032-7","ispublished":"pub","date":"2017-06","pagerange":"19-20","datestamp":"2017-06-14 23:00:40","place_of_pub":"New York, NY","publisher":"ACM","official_url":"http://resolver.caltech.edu/CaltechAUTHORS:20170614-154927009"},

 {"id":82305,"title":"The efficiency of open access in platforms for networked cournot markets","book_title":"IEEE INFOCOM 2017 - IEEE Conference on Computer Communications","event_title":"IEEE International Conference on Computer Communications","creators":[{"name":{"lineage":null,"given":"John Z. F.","honourific":null,"family":"Pang"},"id":"Pang-John-Z-F"},{"name":{"lineage":null,"given":"Hu","honourific":null,"family":"Fu"},"id":"Fu-Hu"},{"name":{"lineage":null,"given":"Won I.","honourific":null,"family":"Lee"},"id":"Lee-Won-I"},{"name":{"lineage":null,"given":"Adam","honourific":null,"family":"Wierman"},"id":"Wierman-A"}],"isbn":"978-1-5090-5336-0","ispublished":"pub","date":"2017-05","pagerange":"1-9","datestamp":"2017-10-12 22:42:03","place_of_pub":"Piscataway, NJ","publisher":"IEEE","official_url":"http://resolver.caltech.edu/CaltechAUTHORS:20171012-094453409"},

{"id":64522,"title":"Distributed optimization decomposition for joint economic dispatch and frequency regulation","book_title":"54th IEEE Conference on Decision and Control (CDC)","event_title":"54th IEEE Conference on Decision and Control (CDC)","creators":[{"orcid":"0000-0001-9207-1890","name":{"lineage":null,"given":"Desmond","honourific":null,"family":"Cai"},"id":"Cai-Desmond-W-H"},{"orcid":"0000-0003-1568-1833","name":{"lineage":null,"given":"Enrique","honourific":null,"family":"Mallada"},"id":"Mallada-E"},{"orcid":null,"name":{"lineage":null,"given":"Adam","honourific":null,"family":"Wierman"},"id":"Wierman-A"}],"isbn":"978-1-4799-7884-7","ispublished":"pub","date":"2015-12","pagerange":"15-22","datestamp":"2016-02-19 00:39:06","place_of_pub":"Piscataway, NJ","publisher":"IEEE","official_url":"http://resolver.caltech.edu/CaltechAUTHORS:20160217-073125386"},

{"id":76616,"title":"Prices and Subsidies in the Sharing Economy","book_title":"Proceedings of the 26th International Conference on World Wide Web - WWW '17","event_title":"26th International Conference on World Wide Web - WWW '17","creators":[{"name":{"lineage":null,"given":"Zhixuan","honourific":null,"family":"Fang"},"id":"Fang-Zhixuan"},{"name":{"lineage":null,"given":"Longbo","honourific":null,"family":"Huang"},"id":"Huang-Longbo"},{"name":{"lineage":null,"given":"Adam","honourific":null,"family":"Wierman"},"id":"Wierman-A"}],"isbn":"978-1-4503-4913-0 ","ispublished":"pub","date":"2017-04","pagerange":"53-62","datestamp":"2017-04-17 22:08:19","place_of_pub":"New York, NY","publisher":"ACM","official_url":"http://resolver.caltech.edu/CaltechAUTHORS:20170417-144012765"}
];
const people = {
  facultyCollaborators: [
    { name: "Steven H. Low",
      position: "Professor of Computing and Mathematical Sciences & Electrical Engineering",
      imageClass: "steven-low",
      education: "B.S., Cornell University, 1987; M.S., University of California, 1989; Ph.D., 1992. Associate Professor, Caltech, 2000-06; Professor, 2006-.",
      link: "http://netlab.caltech.edu"
    },
    {
      name: "Venkat Chandrasekaran",
      position: "Professor of Computing and Mathematical Sciences & Electrical Engineering",
      imageClass: "vankat-chandrasekaran",
      education: "B.A., Rice University, 2005; B.S., 2005; M.S., Massachusetts Institute of Technology, 2007; Ph.D., 2011. Assistant Professor, Caltech, 2012-17; Professor, 2017-.",
      link: "http://www.eas.caltech.edu/people/venkatc"
    },
    {
      name: "Adam Wierman",
      position: "Professor of Computing and Mathematical Sciences",
      imageClass: "adam-wierman",
      education: "B.S., Carnegie Mellon University, 2001; M.S., 2004; Ph.D., 2007. Assistant Professor, Caltech, 2007-12; Professor, 2012-; Executive Officer, 2015-; Associate Director, 2015-16; Director, 2016-.",
      link: "http://www.eas.caltech.edu/people/adamw"
    },
    {
      name: "Yisong Yue",
      position: "Assistant Professor of Computing and Mathematical Sciences",
      imageClass: "yisong-yue",
      education: "B.S., University of Illinois, 2005; Ph.D., Cornell University, 2010. Caltech, 2014-.",
      link: "http://eas.caltech.edu/people/yyue"
    }
  ],
};


export default Ember.Service.extend({
  getPeople() {
    return people;
  },

  getPublications() {
    return publications;
  }
});
